MVC_PracticeExam_02_Solution/AuctionWebApplication/Models/Bid.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace AuctionWebApplication.Models
{
    public class Bid
    {
        [Required]
        public int itemNumber { get; set; }
        [Required]
        public int bidPrice { get; set; }
        [Required]
        [MinLength(4)]
        public string bidCustomName { get; set; }
        [Required]
        [Range(8,8)]
        public int bidCustomPhone { get; set; }
        public AuktionServiceReference.AuctionItem Auktion { get; set; }
    }
}

MVC_PracticeExam_02_Solution/AuctionWebApplication/Controllers/AuktionController.cs
using AuctionWebApplication.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AuctionWebApplication.Controllers
{
    public class AuktionController : Controller
    {
        AuktionServiceReference.AuctionsServiceClient service = new AuktionServiceReference.AuctionsServiceClient();
        // GET: Auktion
        [HttpGet]
        public ActionResult ShowAllAuktions()
        {
            return View(service.GetAllAuctionItems());
        }
        [HttpGet]
        public ActionResult Bid(int id)
        {
            Bid b = new Bid();
            b.Auktion = service.GetAuctionItem(id);
            Session["Id"] = id;
            Session["CurrentBid"] = b.Auktion;
            return View(b);
        }
        [HttpPost]
        public ActionResult Bid(Bid bid)
        {
            if (Session["CurrentBid"] == null)
            {
                return RedirectToAction("ShowAllAuktions");
            }
            bid.Auktion = (AuktionServiceReference.AuctionItem)Session["CurrentBid"];
            bid.Auktion.BidTimestamp = DateTime.Now;
            service.ProvideBid(bid.Auktion.ItemNumber, bid.bidPrice, bid.bidCustomName, bid.bidCustomPhone.ToString());
            int id = int.Parse(Session["Id"].ToString());
            return RedirectToAction("Bid", id);
        }
        [HttpPost]
        public ActionResult SeAlleBud(string username)
        {
            if (username == null)
            {
                return RedirectToAction("ShowAllAuktions");
            }
            List<AuktionServiceReference.AuctionItem> result = new List<AuktionServiceReference.AuctionItem>();
            foreach (var item in service.GetAllAuctionItems())
            {
                if (item.BidCustomName == username)
                {
                    result.Add(item);
                }
            }
            return View(result);
        }

    }
}

MVC_PracticeExam_02_Solution/AuctionWebApplication/Views/Auktion/Bid.cshtml
@model AuctionWebApplication.Models.Bid

@{
    ViewBag.Title = "Bid";
}

<h2>Bid</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Auktion.ItemNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Auktion.ItemDescription)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Auktion.RatingPrice)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Auktion.BidCustomName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Auktion.BidPrice)
        </th>
    </tr>
    <tr>
        <th>
            @Html.DisplayFor(model => model.Auktion.ItemNumber)
        </th>
        <th>
            @Html.DisplayFor(model => model.Auktion.ItemDescription)
        </th>
        <th>
            @Html.DisplayFor(model => model.Auktion.RatingPrice)
        </th>
        <th>
            @Html.DisplayFor(model => model.Auktion.BidCustomName)
        </th>
        <th>
            @Html.DisplayFor(model => model.Auktion.BidPrice)
        </th>
    </tr>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">

            <div class="form-group">
                @Html.LabelFor(model => model.bidPrice, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.bidPrice, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.bidPrice, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.bidCustomName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.bidCustomName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.bidCustomName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.bidCustomPhone, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.bidCustomPhone, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.bidCustomPhone, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
</table>
@using (Html.BeginForm("SeAlleBud","Auktion"))
{
    @Html.TextBox("username")
    <input type="submit" value="Find Bids" />
}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MVC_PracticeExam_02_Solution/AuctionWebApplication/Views/Auktion/SeAlleBud.cshtml
@model IEnumerable<AuctionWebApplication.AuktionServiceReference.AuctionItem>

@{
    ViewBag.Title = "SeAlleBud";
}

<h2>SeAlleBud</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.BidCustomName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BidCustomPhone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BidPrice)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BidTimestamp)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ItemDescription)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ItemNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RatingPrice)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.BidCustomName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BidCustomPhone)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BidPrice)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BidTimestamp)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ItemDescription)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ItemNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RatingPrice)
        </td>
    </tr>
}

</table>

MVC_PracticeExam_02_Solution/AuctionWebApplication/Views/Auktion/ShowAllAuktions.cshtml
@model IEnumerable<AuctionWebApplication.AuktionServiceReference.AuctionItem>

@{
    ViewBag.Title = "ShowAllAuktions";
}

<h2>ShowAllAuktions</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.BidCustomName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BidCustomPhone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BidPrice)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BidTimestamp)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ItemDescription)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ItemNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RatingPrice)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.BidCustomName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BidCustomPhone)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BidPrice)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BidTimestamp)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ItemDescription)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ItemNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RatingPrice)
        </td>
        <td>
            @Html.ActionLink("Bid", "Bid", new {  id=item.ItemNumber }) 
        </td>
    </tr>
}

</table>

MVC_PracticeExam_02_Solution/AuctionWebApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>